"""
Experiment Report Generator.

Generates markdown reports with embedded charts and summary tables.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

from .collector import ExperimentResult


class ExperimentReporter:
    """
    Generates markdown reports from experiment results.

    Output includes:
    - Summary table of all experiments
    - Best model highlights
    - Horizon analysis
    - Embedded chart references
    """

    def __init__(self, results: List[ExperimentResult], output_dir: str):
        self.results = results
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        chart_files: Optional[Dict[str, str]] = None,
        filename: str = "experiment_report.md"
    ) -> str:
        """
        Generate a complete markdown report.

        Args:
            chart_files: Dict mapping chart name to relative file path.
            filename: Output filename.

        Returns:
            Path to generated report.
        """
        lines = []

        # Header
        lines.append("# Experiment Analysis Report\n")
        lines.append(f"> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

        # Experiment info
        if self.results:
            r0 = self.results[0]
            lines.append("## Experiment Setup\n")
            lines.append(f"- **Dataset**: {r0.dataset_name}")
            lines.append(f"- **Input Length**: {r0.input_len}")
            lines.append(f"- **Output Length**: {r0.output_len}")
            if r0.measurement_lag:
                lines.append(f"- **Measurement Lag**: {r0.measurement_lag}")
            lines.append(f"- **Task Type**: {'Soft Sensor' if r0.is_soft_sensor else 'Forecasting'}")
            lines.append(f"- **Total Experiments**: {len(self.results)}")
            lines.append("")

        # Summary table
        lines.append("## Results Summary\n")
        lines.append(self._generate_summary_table())
        lines.append("")

        # Best model
        lines.append("## Best Model\n")
        lines.append(self._generate_best_model_section())
        lines.append("")

        # Horizon analysis
        horizon_section = self._generate_horizon_section()
        if horizon_section:
            lines.append("## Horizon Analysis\n")
            lines.append(horizon_section)
            lines.append("")

        # Zone analysis (soft sensor)
        zone_section = self._generate_zone_section()
        if zone_section:
            lines.append("## Estimation vs Prediction Zone\n")
            lines.append(zone_section)
            lines.append("")

        # Charts
        if chart_files:
            lines.append("## Visualizations\n")
            for name, path in chart_files.items():
                rel_path = os.path.relpath(path, self.output_dir) if os.path.isabs(path) else path
                lines.append(f"### {name}\n")
                lines.append(f"![{name}]({rel_path})\n")

        # Footer
        lines.append("---\n")
        lines.append("*Generated by BasicTS Analysis Module*\n")

        report_content = "\n".join(lines)
        save_path = self.output_dir / filename
        with open(save_path, "w", encoding="utf-8") as f:
            f.write(report_content)

        print(f"Report saved: {save_path}")
        return str(save_path)

    def _generate_summary_table(self) -> str:
        """Generate markdown table of all results."""
        # Determine available metrics
        metrics = []
        if self.results:
            overall = self.results[0].metrics.get("overall", {})
            metrics = list(overall.keys())

        # Header
        header = "| Model | Config | " + " | ".join(metrics) + " |"
        separator = "|" + "------|" * 2 + "------|" * len(metrics)

        rows = [header, separator]
        for r in self.results:
            overall = r.metrics.get("overall", {})
            values = [f"{overall.get(m, 0):.4f}" for m in metrics]
            row = f"| {r.model_name} | {r.config_label} | " + " | ".join(values) + " |"
            rows.append(row)

        return "\n".join(rows)

    def _generate_best_model_section(self) -> str:
        """Identify and describe the best model."""
        if not self.results:
            return "No results available."

        # Best by R2
        best_r2 = max(self.results, key=lambda r: r.metrics.get("overall", {}).get("R2", -999))
        r2_val = best_r2.metrics.get("overall", {}).get("R2", 0)

        # Best by RMSE
        best_rmse = min(self.results, key=lambda r: r.metrics.get("overall", {}).get("RMSE", 999))
        rmse_val = best_rmse.metrics.get("overall", {}).get("RMSE", 0)

        lines = []
        lines.append(f"- **Best R²**: {best_r2.model_name} ({best_r2.config_label}) — R² = {r2_val:.4f}")
        lines.append(f"- **Best RMSE**: {best_rmse.model_name} ({best_rmse.config_label}) — RMSE = {rmse_val:.4f}")

        return "\n".join(lines)

    def _generate_horizon_section(self) -> Optional[str]:
        """Generate horizon-wise comparison table."""
        horizons = sorted(set(
            key for r in self.results for key in r.metrics if key.startswith("horizon_")
        ))

        if not horizons:
            return None

        # Table: Model | Config | h1 R2 | h3 R2 | h6 R2 | ...
        h_labels = [f"h{h.split('_')[1]} R2" for h in horizons]
        header = "| Model | Config | " + " | ".join(h_labels) + " |"
        separator = "|" + "------|" * 2 + "------|" * len(horizons)

        rows = [header, separator]
        for r in self.results:
            values = []
            for h in horizons:
                val = r.metrics.get(h, {}).get("R2", 0)
                values.append(f"{val:.4f}")
            row = f"| {r.model_name} | {r.config_label} | " + " | ".join(values) + " |"
            rows.append(row)

        return "\n".join(rows)

    def _generate_zone_section(self) -> Optional[str]:
        """Generate estimation vs prediction zone comparison."""
        ss_results = [r for r in self.results if r.is_soft_sensor and r.measurement_lag]
        if not ss_results:
            return None

        header = "| Model | Config | Estimation Zone R² | Prediction Zone R² | Δ |"
        separator = "|------|------|------|------|------|"

        rows = [header, separator]
        for r in ss_results:
            lag = r.measurement_lag
            est_vals = []
            pred_vals = []

            for key, values in r.metrics.items():
                if not key.startswith("horizon_"):
                    continue
                h = int(key.split("_")[1])
                val = values.get("R2", None)
                if val is None:
                    continue
                if h <= lag:
                    est_vals.append(val)
                else:
                    pred_vals.append(val)

            est_avg = np.mean(est_vals) if est_vals else 0
            pred_avg = np.mean(pred_vals) if pred_vals else 0
            delta = est_avg - pred_avg

            row = f"| {r.model_name} | {r.config_label} | {est_avg:.4f} | {pred_avg:.4f} | {delta:+.4f} |"
            rows.append(row)

        return "\n".join(rows)
